name: Gradle Package

on:
  release:
    types: [published]  # Spustí se, když se release publikuje

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build all projects
        run: ./gradlew shadowJar

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"

      # Nahraj Bukkit JAR soubor
      - name: Upload Bukkit JAR as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}  # Použije URL existujícího releasu
          asset_path: unlimitedchats-bukkit/build/libs/unlimitedchats-bukkit-${{ steps.get_version.outputs.version }}.jar
          asset_name: unlimitedchats-bukkit-${{ steps.get_version.outputs.version }}.jar
          asset_content_type: application/java-archive

      # Nahraj Bungee JAR soubor
      - name: Upload Bungee JAR as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: unlimitedchats-bungee/build/libs/unlimitedchats-bungee-${{ steps.get_version.outputs.version }}.jar
          asset_name: unlimitedchats-bungee-${{ steps.get_version.outputs.version }}.jar
          asset_content_type: application/java-archive

      # Nahraj Velocity JAR soubor
      - name: Upload Velocity JAR as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: unlimitedchats-velocity/build/libs/unlimitedchats-velocity-${{ steps.get_version.outputs.version }}.jar
          asset_name: unlimitedchats-velocity-${{ steps.get_version.outputs.version }}.jar
          asset_content_type: application/java-archive
